services:

  backend:
    build: .
    container_name: cloudstore-app

    ports:
      - "5001:5001"


    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      fakestore.url: ${FAKESTORE_URL}
      SERVER_PORT: 5001