spring.application.name=CloudStoreProject


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
fakestore.url=https://yahyatesting-env.eba-sarnymwd.eu-north-1.elasticbeanstalk.com/products

server.port=8080