spring.application.name=CloudStoreProject


spring.datasource.url=jdbc:mysql://localhost:3306/products
spring.datasource.username=root
spring.datasource.password=B#3utreee1234

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
fakestore.url=https://yahyatesting-env.eba-sarnymwd.eu-north-1.elasticbeanstalk.com/products
server.port=5000